#!/bin/bash

if [[ -n "${PPG_DEBUG}" ]]; then
	set -x
fi

usage() {
	echo "Usage: ppg COMMAND [OPTIONS] [TARGET]"
	echo 
	echo "ppg commands are:"

	cat <<\EOF | sed -e 's/^/    /'

For development environments

  init-devenv      Prepares a development/test environment for commits
  commit           Commits though to git
  schedule         Schedule a commit for merge to production

For puppet clients

  clone        Clones and inits a client environment
  init         Prepares a client environment after a "git clone"
  pullapply    Updates and applies config updates
  apply        Apply changes manually

EOF
}

# RHEL6/CentOS6 does not have /usr/bin/realpath
PPG_EXEC_PATH=$( dirname $(readlink -f "${BASH_SOURCE[0]}" ) )

cmd=
case "$#" in
0)	usage 
    ;;
*)	cmd="$1"
	shift
	case "$cmd" in
	-v|--v|--ve|--ver|--vers|--versi|--versio|--version)
		echo "ppg version @@PPG_VERSION@@"
		exit 0 ;;
	-h|--help)
		usage
		exit 0;;
	-*)
		echo >&2 "ERROR: Unknown option $cmd"
		usage
		exit 1;
	esac
	
	if [[ -x "$PPG_EXEC_PATH/ppg-$cmd" ]]; then
		exec "$PPG_EXEC_PATH/ppg-$cmd" "$@"
		exit $?
	else
		echo >&2 "ERROR: Unknown command $cmd"
		usage
		exit 1;
	fi
	;;
esac
