#!/bin/bash
#
# Reends a remote url parameter in a format appropriate for ssh/scp
# for example: 
#  
#   ppg-pull-reports [ --nodelete ] puppeteer.foo.com:/var/lib/ppg/reports/
#
if [[ -n "${PPG_DEBUG}" ]]; then
	set -x
fi
PPG_EXEC_PATH=$( dirname $(readlink -f "${BASH_SOURCE[0]}" ) )

reportsdir=/var/lib/ppg/reports-import

if [ "$1" == "--nodelete" ]; then
	delete=''
    shift
else
	# flag to lftp mirror
    delete='--Remove-source-files'
fi

remoteurl=$1

lftp -c "mirror -${delete} sftp://${remoteurl}" ${reportsdir}
