#!/bin/bash

PPG_EXEC_PATH=$( dirname $(realpath "${BASH_SOURCE[0]}" ) )
GIT_EXEC_PATH=$(git --exec-path)
GIT_DIR=$(git rev-parse --git-dir)

if [ -z "$GIT_DIR" ]; then
	echo >&2 "Not in a git checkout"
	exit 1
fi

## we walk the options to extract any ppg-commit options
## any other option is passed on to git-commit
immediate=
gitcommitargs=
while test $# != 0
do
	myvar=
	case "$1" in
	--immediate)
        immediate=t
        myvar=t
		;;
	esac
	if [ -z "$myvar" ]; then
		# array push
		gitcommitargs[${#gitcommitargs[@]}]="$1"
	fi
	shift
done

# these may not exist
production_sha1=$( git rev-parse --revs-only refs/heads/production 2>/dev/null )
orig_production_sha1=$( git rev-parse --revs-only refs/heads/origin/production 2>/dev/null )

if [ -n "$production_sha1" -a -n "$orig_production_sha1" ]; then
	mb=$(git merge-base $production_sha1 $orig_production_sha1)
	if [[ "$mb" -eq "$production_sha1" ]]; then
		echo "Fast-forwarding your local production head to match origin/production"
		$GIT_EXEC_PATH/git-update-ref -m "ppg ff to origin/production" refs/heads/production $orig_production_sha1 $production_sha1 || exit 1
		production_sha1=$orig_production_sha1
	elif [[ "$mb" -ne "$origin_production_sha1" ]]; then
		echo >&2 "ERROR: production and origin/production have diverged!"
		exit 1
	fi
fi

if [ -n "$immediate" ]; then
	# sanity-check we are on master
	headname=$(git rev-parse --symbolic-full-name --revs-only HEAD)
	if [ "$headname" -ne "refs/heads/headname" ]; then
		echo >&2 "ERROR: can only issue --immediate commit from the master branch!"
		exit 1
	fi
fi

$PPG_EXEC_PATH/ppg-validate-staged-files || exit 1

export PPG_COMMIT=yes
git commit "${gitcommitargs[@]}" || exit 1

if [ -n "$immediate" ]; then
	if [ -z "$production_sha1" ]; then
		echo "Creating production branch"
		git branch production master
		production_sha1=$(git rev-parse --revs-only production)
	else
		# ensure we can ff
		head_sha1=$(git rev-parse --revs-only master)
	    mb=$(git merge-base $production_sha1 refs/heads/master)
		if [[ "$mb" -ne "$production_sha1" ]]; then
			echo >&2 "ERROR: cannot fast-forward master to production"
			exit 1
		fi
		$GIT_EXEC_PATH/git-update-ref -m "ppg immediate commit" refs/heads/production $head_sha1 $production_sha1 || exit 1
	fi
fi
