#!/bin/bash

if [[ -n "${PPG_DEBUG}" ]]; then
	set -x
fi

if [[ -z "$1" ]]; then
	echo >&2 "ERROR: needs base path parameter"
	exit 1
fi

base_repo=$1

mkdir -p $1
echo "Preparing the repository for your Puppet configurations"
git --git-dir=${base_repo}/puppet.git init --bare

echo "Preparing the directory for reports"
mkdir ${base_repo}/reports

echo
echo "Make reports.git writable by the user/group that clients"
echo "use to connect."
