#!/bin/bash

GIT_DIR=$(git rev-parse --git-dir)

if [ -z "$GIT_DIR" ]; then
	echo >&2 "Not in a git checkout"
	exit 1
fi

cat << 'EOF' > $GIT_DIR/hooks/pre-commit.tmp$$
#!/bin/sh

if [ -z "$PPG_COMMIT" ]; then
     echo >&2 On this repository, use ppg commit instead of git commit
     exit 1
fi

EOF

if ! cmp $GIT_DIR/hooks/pre-commit $GIT_DIR/hooks/pre-commit.tmp$$ ; then
	cp $GIT_DIR/hooks/pre-commit{,.backup-$(date +%Y%m%d%H%M)}
	mv $GIT_DIR/hooks/pre-commit.tmp$$ $GIT_DIR/hooks/pre-commit
fi
chmod ugo+x $GIT_DIR/hooks/pre-commit
