#!/bin/bash

PPG_EXEC_PATH=$( dirname $(realpath "${BASH_SOURCE[0]}" ) )
GIT_EXEC_PATH=$(git --exec-path)
GIT_DIR=$(git rev-parse --git-dir)

if [ -z "$GIT_DIR" ]; then
	echo >&2 "Not in a git checkout"
	exit 1
fi

## we walk the options to extract any ppg-commit options
## any other option is passed on to git-commit
immediate=
gitcommitargs=
while test $# != 0
do
	myvar=
	case "$1" in
	--immediate)
        immediate=t
        myvar=t
		;;
	esac
	if [ -z "$myvar" ]; then
		# array push
		gitcommitargs[${#gitcommitargs[@]}]="$1"
	fi
	shift
done

# these may not exist
production_sha1=$(git rev-parse --revs-only refs/heads/production 2>/dev/null)
orig_production_sha1=$(git rev-parse --revs-only refs/heads/origin/production \
	2>/dev/null )

if [ -n "$production_sha1" -a -n "$orig_production_sha1" ]; then
	if [ "$production_sha1" != "$orig_production_sha1" ]; then
		echo "Fast-forwarding local production head to match origin/production"
		if ! git push . $orig_production_sha1:refs/heads/production ; then
			echo >&2 "ERROR: production and origin/production have diverged!"
			exit 1
		fi
	fi
fi

if [ -n "$immediate" ]; then
	# sanity-check we are on master
	headname=$(git rev-parse --symbolic-full-name --revs-only HEAD)
	if [ "$headname" != "refs/heads/master" ]; then
		echo >&2 "ERROR: can only issue immediate commit on the master branch!"
		exit 1
	fi
fi

$PPG_EXEC_PATH/ppg-validate-staged-files || exit 1

export PPG_COMMIT=yes
git commit "${gitcommitargs[@]}" || exit 1

if [ -n "$immediate" ]; then
	if [ -z "$production_sha1" ]; then
		echo "Creating production branch"
		git branch production master
		production_sha1=$(git rev-parse --revs-only production)
	else
		if [[ $(git log --oneline production..HEAD|wc -l) -gt 1 ]]; then
			echo
			echo WARNING: More than one change will be scheduled for immediate
			echo          deployment. Please review the list of commits.
			echo
			git log --pretty=short --stat production..HEAD
			echo
			echo -n "Is this correct? [Ny] "
			read correct
			if [[ "${correct:0:1}" != 'Y' ]] && [[ "${correct:0:1}" != 'y' ]];
			    then
     			echo Cancelling immediate schedule. 
     			exit 1
			fi
		fi
		if ! git push . $head_sha1 refs/heads/production ; then
			echo >&2 "ERROR: cannot fast-forward master to production"
			echo >&2 "       make sure the branches have not diverged"
			exit 1
		fi
	fi
	echo "Immediate commit successful -- remember to git push --all"
	echo "to publish the changes on the gold server."
else
	echo 'Checking for scheduled updates to the production branch...'
    $PPG_EXEC_PATH/ppg-ff-scheduled
fi
